# DOWNLOAD AND LOAD THE DATASET

In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# IMAGE AUGMENTATION

In [ ]:
train_datagen = ImageDataGenerator(rescale=1./255,
                                   zoom_range=0.2,
                                   horizontal_flip=True)

In [ ]:
test_datagen = ImageDataGenerator(rescale=1./255)

In [ ]:
xtrain = train_datagen.flow_from_directory('flowers',
                                           target_size=(64,64),
                                           class_mode='categorical',
                                           batch_size=100)

Found 4317 images belonging to 5 classes.


In [ ]:
xtest = train_datagen.flow_from_directory('flowers',
                                           target_size=(64,64),
                                           class_mode='categorical',
                                           batch_size=100)

Found 4317 images belonging to 5 classes.


# CNN MODEL

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Convolution2D,MaxPooling2D,Flatten,Dense

# ADDING LAYERS

In [ ]:
model = Sequential()
model.add(Convolution2D(32,(3,3),activation='relu',input_shape=(64,64,3)))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Flatten())
model.add(Dense(300,activation='relu'))
model.add(Dense(150,activation='relu'))
model.add(Dense(5,activation='softmax'))

# COMPILING THE MODEL

In [ ]:
model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

# FITTING THE MODEL AND TUNING

In [ ]:
from keras.callbacks import EarlyStopping, ReduceLROnPlateau

In [ ]:
early_stopping = EarlyStopping(monitor='val_accuracy',
                        patience=5)
reduce_lr = ReduceLROnPlateau(monitor='val_accuracy',
                        patience=5,
                        factor=0.5,min_lr=0.00001)

callback = [reduce_lr,early_stopping]

In [ ]:
model.fit_generator(xtrain,
                    steps_per_epoch=len(xtrain),
                    epochs=10,
                    validation_data=xtest,
                    validation_steps=len(xtest))

C:\Users\Admin\AppData\Local\Temp/ipykernel_4264/2338346036.py:1: UserWarning: `Model.fit_generator` is deprecated and will be removed in a future version. Please use `Model.fit`, which supports generators.
  model.fit_generator(xtrain,


Epoch 1/10
44/44 [==============================] - 454s 10s/step - loss: 1.5832 - accuracy: 0.3841 - val_loss: 1.1629 - val_accuracy: 0.5240
Epoch 2/10
44/44 [==============================] - 162s 4s/step - loss: 1.1591 - accuracy: 0.5237 - val_loss: 1.1496 - val_accuracy: 0.5332
Epoch 3/10
44/44 [==============================] - 155s 4s/step - loss: 1.0605 - accuracy: 0.5784 - val_loss: 0.9839 - val_accuracy: 0.6155
Epoch 4/10
44/44 [==============================] - 161s 4s/step - loss: 0.9860 - accuracy: 0.6134 - val_loss: 0.9281 - val_accuracy: 0.6324
Epoch 5/10
44/44 [==============================] - 163s 4s/step - loss: 0.9186 - accuracy: 0.6498 - val_loss: 0.8870 - val_accuracy: 0.6551
Epoch 6/10
44/44 [==============================] - 150s 3s/step - loss: 0.8737 - accuracy: 0.6625 - val_loss: 0.8345 - val_accuracy: 0.6745
Epoch 7/10
44/44 [==============================] - 158s 4s/step - loss: 0.8350 - accuracy: 0.6866 - val_loss: 0.8257 - val_accuracy: 0.6778
Epoch 8/10
4

# SAVING THE MODEL

In [ ]:
model.save('Flower.h5')

# TESTING THE MODEL

In [ ]:
import numpy as np
from tensorflow.keras.preprocessing import image

In [ ]:
img = image.load_img('flowers/daisy/14163875973_467224aaf5_m.jpg',target_size=(64,64))

In [ ]:
x = image.img_to_array(img)
x

array([[[ 35.,  36.,  30.],
        [ 33.,  34.,  28.],
        [ 24.,  25.,  19.],
        ...,
        [ 17.,  20.,   0.],
        [ 11.,  18.,   0.],
        [ 12.,  21.,   0.]],

       [[ 43.,  44.,  38.],
        [ 41.,  42.,  36.],
        [ 26.,  27.,  21.],
        ...,
        [ 16.,  25.,   6.],
        [ 12.,  28.,   0.],
        [ 16.,  33.,   0.]],

       [[ 48.,  49.,  41.],
        [ 43.,  44.,  36.],
        [ 28.,  29.,  21.],
        ...,
        [ 24.,  36.,  14.],
        [ 27.,  46.,   0.],
        [ 30.,  49.,   3.]],

       ...,

       [[ 33.,  43.,   9.],
        [ 49.,  67.,  15.],
        [ 44.,  64.,   5.],
        ...,
        [136., 135., 140.],
        [136., 135., 140.],
        [146., 145., 150.]],

       [[ 71.,  54.,  44.],
        [ 61.,  61.,  51.],
        [ 45.,  68.,   0.],
        ...,
        [143., 142., 140.],
        [148., 147., 145.],
        [158., 158., 156.]],

       [[ 32.,  21.,   3.],
        [106.,   5.,  35.],
        [ 62.,  

In [ ]:
x = np.expand_dims(x,axis=0)
x

array([[[[ 35.,  36.,  30.],
         [ 33.,  34.,  28.],
         [ 24.,  25.,  19.],
         ...,
         [ 17.,  20.,   0.],
         [ 11.,  18.,   0.],
         [ 12.,  21.,   0.]],

        [[ 43.,  44.,  38.],
         [ 41.,  42.,  36.],
         [ 26.,  27.,  21.],
         ...,
         [ 16.,  25.,   6.],
         [ 12.,  28.,   0.],
         [ 16.,  33.,   0.]],

        [[ 48.,  49.,  41.],
         [ 43.,  44.,  36.],
         [ 28.,  29.,  21.],
         ...,
         [ 24.,  36.,  14.],
         [ 27.,  46.,   0.],
         [ 30.,  49.,   3.]],

        ...,

        [[ 33.,  43.,   9.],
         [ 49.,  67.,  15.],
         [ 44.,  64.,   5.],
         ...,
         [136., 135., 140.],
         [136., 135., 140.],
         [146., 145., 150.]],

        [[ 71.,  54.,  44.],
         [ 61.,  61.,  51.],
         [ 45.,  68.,   0.],
         ...,
         [143., 142., 140.],
         [148., 147., 145.],
         [158., 158., 156.]],

        [[ 32.,  21.,   3.],
       

In [ ]:
model.predict(x)

array([[1., 0., 0., 0., 0.]], dtype=float32)

In [ ]:
op = ['daisy','dandelion','rose','sunflower','tulip']
pred = np.argmax(model.predict(x))
op[pred]

'daisy'

In [ ]:
img = image.load_img('flowers/rose/10894627425_ec76bbc757_n.jpg',target_size=(64,64))
x = image.img_to_array(img)
x = np.expand_dims(x,axis=0)
pred = np.argmax(model.predict(x))
op[pred]

'rose'

In [ ]:
img = image.load_img('flowers/dandelion/16041975_2f6c1596e5.jpg',target_size=(64,64))
x = image.img_to_array(img)
x = np.expand_dims(x,axis=0)
pred = np.argmax(model.predict(x))
op[pred]

'dandelion'